config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  devise_for :users
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  
  resources :categories, :only => [:index, :show]
  resources :recipes, :only => [:index, :show], path: 'recettes' do 
  	member do 
  		post 'publish'
  		post 'unpublish'
  	end
  end

  root to: "welcome#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/recipe.rb
class Recipe < ApplicationRecord
	# Frendly id. Transform things like /recipes/1 into /recipses/gateau-au-chocolat
	extend FriendlyId
  	friendly_id :title, use: :slugged

	# pagination (4 lines of 3)
  	paginates_per 12
  	
  	# full text postgress search
	include PgSearch::Model
	pg_search_scope :search_by_title, 
					against: :title,
					using: { tsearch: { dictionary: 'french' } }

	# Hit tracker
	acts_as_punchable

	# has many though relation with category
	has_many :categories_recipe, dependent: :destroy
	has_many :categories, through: :categories_recipe

	# ActiveStorage photo attachement
	has_one_attached :photo

	# Validation
	validates :title, presence: true
	validates :photo, presence: true
	validates :story, presence: true
	validates :ingredients, presence: true
	validates :complexity, presence: true
	validates :instructions, presence: true
	validates :preparation_time, presence: true
	validates :preparation_time, numericality: { only_integer: true, :greater_than_or_equal_to => 1 }
	validates :complexity, numericality: { only_integer: true, :greater_than_or_equal_to => 1, :less_than_or_equal_to => 3 }

	# Scope definition
	scope :published, -> { where(public: true) }
	scope :unpublished, -> { where(public: false) }

	# Give on random item
	def self.random
		offset(rand(count))
    end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: [:show, :publish, :unpublish]
  before_action :authorize_access, only: [:show]
  before_action :authorize_action, only: [:publish, :unpublish]

  # GET /recipes
  def index
    # If Search paramater, then @recipes will be set to the list of matching public recipes, order by title.
    # Else @recipes will be set to the list of all public recipes, order by title.
    if params[:search]&& !params[:search].empty?
      @recipes = Recipe.published.search_by_title(params[:search]).order(:title).page params[:page]
    else
      @recipes = Recipe.published.order(:title).page params[:page]
      # Get the 4 most popular categories (by recipes count)
      @most_popular_categories = Category.all.order(recipes_count: :desc).limit(4)
    end



    # Set the meta tags of the page. Descirption and keywords include to first 20 recipes
    # TODO: Order the keywords and description by popularity    
    set_meta_tags title: 'Recettes',
                  description: 'Toutes les recettes: ' + @recipes.map(&:title).join(', ') + ' ...',
                  keywords: @recipes.map(&:title).join(', '),
                  og: {
                    title: :title,
                    site_name: :site,
                    url: request.original_url,
                    description: :description,
                    locale: "fr_FR",
                    type: "website"
                  }
  end

  # GET /recipes/1
  def show
    # Get the related categories for that recipe, order by title
    @categories = @recipe.categories.all.order(:title)

    @recipe.punch(request)

    # Set the meta tags of the page. 
    # Descirption is the stripped down version of the recipe story (The first 160 char)
    # keywords are the related categories.
    # TODO: Order the keywords by popularity   
    set_meta_tags title: 'Recette: ' + @recipe.title,
                  description: helpers.no_markdown(@recipe.story)[0..160],
                  keywords: @categories.map(&:title).join(', '),
                  og: {
                    title: :title,
                    site_name: :site,
                    image: url_for(@recipe.photo),
                    url: request.original_url,
                    description: :description,
                    locale: "fr_FR",
                    type: "article",
                    article: {
                      published_time: @recipe.created_at
                    }
                  }
  end

  # POST /recipes/id/publish
  # Publish the recipe, set the created time to now. redirect tot he show page of the recipe
  def publish
    @recipe.public = true
    @recipe.created_at = Time.now  
    @recipe.save
    redirect_to @recipe
  end

  # POST /recipes/id/unpublish
  # Unpublish the recipe, redirect tot he show page of the recipe
  def unpublish
    @recipe.public = false
    @recipe.save
    redirect_to @recipe
  end

  private
    def set_recipe
      @recipe = Recipe.friendly.find(params[:id])
    end

    # before show
    # OK if the recipe if it's public or if we are logged (As blog admin)
    # else redirect to 403 page
    def authorize_access
      unless (@recipe.public?  or current_user.present?)
        render file: "#{Rails.root}/public/403.html", layout: false, status: 403
      end
    end

    # before publish, unpublish
    # OK if we are logged (As blog admin)
    # else redirect to 403 page
    def authorize_action
      unless current_user.present?
        render file: "#{Rails.root}/public/403.html", layout: false, status: 403
      end
    end
end

app/helpers/recipes_helper.rb
module RecipesHelper

	# Convert preparation time into human readable string
	def preparation_time_human(recipe)
		convert_time_to_human(recipe.preparation_time)
	end

	# Convert baking time into human readable string
	def baking_time_human(recipe)
		convert_time_to_human(recipe.baking_time)
	end

	# Convert waiting time into human readable string
	def waiting_time_human(recipe)
		convert_time_to_human(recipe.waiting_time)
	end

	# Convert global time into human readable string
	def global_time_human(recipe)
		global_time = recipe.preparation_time.to_i + recipe.waiting_time.to_i + recipe.baking_time.to_i
		convert_time_to_human(global_time)
	end

	# Convert complixity time into human readable string
	def complexity_human(recipe)
		case recipe.complexity
		when 1
			"Simple"
		when 2
			"Moyen"
		when 3
			"Difficile"
		end
	end
end

def convert_time_to_human(integer)
	hours, minutes = integer.to_i.divmod(60)
	if hours == 0
		minutes.to_s + " min"
	elsif minutes == 0
		hours.to_s + "h"
	else
		hours.to_s + "h" + minutes.to_s
	end
end

app/views/recipes/_admin_section.html.erb
<%= render "admin_panel" do %>
	<strong>Recette: <%= @recipe.title %></strong> | 
	<i class="fas fa-eye"></i> <%= @recipe.hits %>
	<div class="w3-bar">
		<%= link_to rails_admin.show_path(model_name: 'recipe', id: @recipe.id), class: "w3-bar-item w3-button w3-mobile" do %>
			<i class="fas fa-user-lock"></i> Ouvrir dans l'admin
		<% end %>	
		<%= link_to rails_admin.edit_path(model_name: 'recipe', id: @recipe.id), class: "w3-bar-item w3-button w3-mobile" do %>
			<i class="fas fa-edit"></i> Modifier
		<% end %>	
		<%= link_to rails_admin.delete_path(model_name: 'recipe', id: @recipe.id), class: "w3-bar-item w3-button w3-mobile" do %>
			<i class="fas fa-trash"></i> Supprimer
		<% end %>	
		<% if @recipe.public? %>
			<%= link_to unpublish_recipe_path(@recipe), method: :post, class: "w3-bar-item w3-button w3-mobile" do %>
				<i class="fas fa-eye-slash"></i> Rendre privée
			<% end %>	
		<% else %>
			<%= link_to publish_recipe_path(@recipe), method: :post, class: "w3-bar-item w3-button w3-mobile" do %>
				<i class="fas fa-eye"></i> Rendre publique
			<% end %>
		<% end %>
	</div>
<% end %>

app/views/recipes/_breadcrumb.html.erb
<nav class="w3-margin">
  <%= link_to root_path do%><i class="fas fa-home"></i><% end %>
  >
  <%= link_to "Recettes", recipes_path %>
  >
  <% @categories.each do |category| %>
  	<%= link_to category.title, category %>
  	<% if category != @categories.last %>
	    x
	  <% end %>
  <% end %>
</nav>

app/views/recipes/_ingredients.html.erb
<h2 class="main-title"><i class="fas fa-apple-alt"></i> Ingredients</h2>
<%= markdown(@recipe.ingredients) %>

app/views/recipes/_instructions.html.erb
<h2 class="main-title"><i class="fas fa-flask"></i> Préparation</h2>
<%= markdown(@recipe.instructions) %>

app/views/recipes/_nav.html.erb
<nav class="w3-container">
  <%= link_to root_path do%><i class="fas fa-home"></i><% end %>
  >
  <%= link_to "Recettes", recipes_path %>
  >
  <% @recipe.categories.each do |category| %>
  	<%= link_to category.title, category %>
  	<% if category != @recipe.categories.last %>
	    x
	  <% end %>
  <% end %>
  > 
</nav>

app/views/recipes/_not_authorized.html.erb
<section class="w3-row">
	<h1>NOT AUTHORISED</h1>
</section>

app/views/recipes/_recipe.html.erb
<section class="w3-row w3-section">
  <article class="w3-col w3-padding l6 m6">
    <h1 class="main-title"><%= @recipe.title.upcase %></h1>
    <%= render "summary" %>
  </article>
  <div class="w3-container w3-col l6 m6">
    <%= image_tag   @recipe.photo.variant(resize_to_fill: [600,450]),
                    class: "w3-image w3-round-xlarge w3-card", 
                    alt: @recipe.title,
                    loading: "lazy",
                    width: "600",
                    height: "450" %>
  </div>
</section>
<section class="recipe-story w3-panel">
  <%= render "story" %>
</section>
<section class="w3-row">
  <div class="recipe-ingredient-and-tool w3-container w3-col l4">
    <%= render "ingredients" %>
    <% if @recipe.tools? %>
      <%= render "tools" %>
    <% end %>
  </div>
  <div class="recipe-instruction w3-container w3-col l8">
    <%= render "instructions" %>
  </div>
</section>
<% if @recipe.tips? %>
  <section class="w3-panel">
    <%= render "tips" %>
  </section>
<% end %>

app/views/recipes/_story.html.erb
<div class="recipe-story-quote">❝</div>
<%= markdown(@recipe.story) %>
<div class="recipe-story-quote w3-right-align">❞</div>

app/views/recipes/_summary.html.erb
<div class="w3-margin-bottom recipe-summary">
	<i>
	<%= @recipe.created_at.to_time.strftime('%d/%m/%Y') %> | 
	<% @categories.each do |category| %>
		<%= link_to category.title, category %>
	    <% if category != @categories.last %>
	      x
	    <% end %>
	<% end %>
	</i>
</div>
<div class="recipe-summary">
		<i class="fas fa-bolt"></i> <strong>Difficulté</strong> | <%= complexity_human(@recipe) %><br>
		<% if @recipe.preparation_time? %>
			<i class="fas fa-play"></i> <strong>Preparation</strong> | <%= preparation_time_human(@recipe) %><br>
		<% end %>
		<% if @recipe.waiting_time? %>
			<i class="fas fa-pause"></i> <strong>Repos</strong> | <%= waiting_time_human(@recipe) %><br>
		<% end %>
		<% if @recipe.baking_time? %>
			<i class="fas fa-fire"></i> <strong>Cuisson</strong> | <%= baking_time_human(@recipe) %><br>
		<% end %>
	</p>
</div>

app/views/recipes/_tips.html.erb
<h2 class="w3-margin-top main-title"><i class="fas fa-lightbulb"></i> Astuces</h2>
<%= markdown(@recipe.tips) %>

app/views/recipes/_tools.html.erb
<h2 class="w3-margin-top main-title"><i class="fas fa-utensils"></i> Ustensiles</h2>
<%= markdown(@recipe.tools) %>

app/views/recipes/index.html.erb
<%= render 'hero_image' %>
<main class="w3-content">
	<nav class="w3-margin">
	  <%= link_to root_path do%><i class="fas fa-home"></i><% end %>
	  > Recettes
	</nav>

	<% if defined?(@most_popular_categories) %>
		<h2 class="main-title  w3-container">CATEGORIES POPULAIRES</h2>
		<section class="w3-row">
			<% @most_popular_categories.each do |category| %>
				<article class="w3-col l3 m4 s6">
					<%= render "category_summary_card", category: category %>
				</article>
			<% end %>
		</section>
		<div class="w3-container">
			<%= render "button_link", link_path: categories_path, link_text: "Toutes les categories" %>
		</div>
	<% end %>


	<h2 class="main-title w3-container">TOUTES LES RECETTES</h2>
	<div class="w3-margin">
		<%= render 'recipes_search' %>
	</div>
	<section class="w3-row">
	<% @recipes.each do |recipe| %>
		<article class="w3-col l4 m6">
	  		<%= render "recipe_summary_card", recipe: recipe %>
	  	</article>
	<% end %>
	</section>
	<%= paginate @recipes%>	
</main>

app/views/recipes/show.html.erb
<main class="w3-content ">
  <%= render 'breadcrumb' %>
  <%= render 'recipe' %>
  <%= render 'breadcrumb' %>
  <% if current_user.present? %>
  	<%= render "admin_section" %>
  <% end %>
</main>