config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  devise_for :users
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  
  resources :categories, :only => [:index, :show]
  resources :recipes, :only => [:index, :show], path: 'recettes' do 
  	member do 
  		post 'publish'
  		post 'unpublish'
  	end
  end

  root to: "welcome#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    # Last 3 publish recipes
  	@latest_published_recipes = Recipe.published.order(created_at: :desc).limit(3)

    # The unpublished recipes
  	@unpublished_recipes = Recipe.unpublished

    # The 4 most popular cateogries (By recipes_count)
  	@most_popular_categories = Category.all.order(recipes_count: :desc).limit(4)

    # One random recipe
  	@random_recipe = Recipe.published.random.first

    # Set the meta tags of the page. 
    # Keywords include everything displayed on the page : The last published recipes, the most popular categories
    set_meta_tags description: "Youpi Poutchi blog" ,
              		keywords: @latest_published_recipes.map(&:title).join(', ') + 
                            ', ' + 
                            @most_popular_categories.map(&:title).join(', '),
                  og: {
                    title: :title,
                    site_name: :site,
                    url: request.original_url,
                    description: :description,
                    locale: "fr_FR",
                    type: "website"
                  }
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/_admin_section.html.erb
<%= render "admin_panel" do %>
	<% unless @unpublished_recipes.empty? %>
	<strong>Recettes non-publiée :</strong>
	<ul>
		<% @unpublished_recipes.each do |recipe| %>
		<li><%= link_to recipe.title, recipe %></li>
		<% end %>
	</ul>
	<% end %>
	<div class="w3-bar">
		<%= link_to rails_admin_path, class: "w3-bar-item w3-button w3-mobile" do %>
			<i class="fas fa-user-lock"></i> Ouvrir l'admin
		<% end %>	
		<%= link_to rails_admin.new_path(model_name: 'recipe'), class: "w3-bar-item w3-button w3-mobile" do %>
			<i class="fas fa-apple-alt"></i> Nouvelle recette
		<% end %>	
		<%= link_to rails_admin.new_path(model_name: 'category'), class: "w3-bar-item w3-button w3-mobile" do %>
			<i class="fas fa-tags"></i> Nouvelle categorie
		<% end %>	
		<%= link_to  destroy_user_session_path, :method => :delete , class: "w3-bar-item w3-button w3-mobile" do %>
			<i class="fas fa-sign-out-alt"></i> Se déconnecter
		<% end %>		
	</div>
<% end %>

app/views/welcome/index.html.erb
<%= render 'hero_image' %>
<main class="w3-content">

	<div class="w3-margin">
		<%= render 'recipes_search' %>
	</div>
	
	<h2 class="main-title w3-container">DERNIERES RECETTES</h2>
	<section class="w3-row">
		<% @latest_published_recipes.each do |recipe| %>
			<article class="w3-col l4 m6">
				<%= render "recipe_summary_card", recipe: recipe %>
			</article>
		<% end %>
	</section>
	<div class="w3-container">
		<%= render "button_link", link_path: recipes_path, link_text: "Toutes les recettes" %>
	</div>

	<h2 class="main-title  w3-container">CATEGORIES POPULAIRES</h2>
	<section class="w3-row">
		<% @most_popular_categories.each do |category| %>
			<article class="w3-col l3 m4 s6">
				<%= render "category_summary_card", category: category %>
			</article>
		<% end %>
	</section>
	<div class="w3-container">
		<%= render "button_link", link_path: categories_path, link_text: "Toutes les categories" %>
	</div>

	
	<h3 class="main-title  w3-container">EN MANQUE D'INSPIRATION ?</h3>
	<section class="w3-row">
		<article class="w3-col l4 m6">
			<%= render "recipe_summary_card", recipe: @random_recipe %>
		</article>
	</section>

	
	<% if current_user.present? %>
		<%= render "admin_section"  %>
	<% end %>
</main>