config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  devise_for :users
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  
  resources :categories, :only => [:index, :show]
  resources :recipes, :only => [:index, :show], path: 'recettes' do 
  	member do 
  		post 'publish'
  		post 'unpublish'
  	end
  end

  root to: "welcome#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/helpers/application_helper.rb
require 'redcarpet'
require 'redcarpet/render_strip'

module ApplicationHelper
	def markdown(text)
		options = [:hard_wrap, :filter_html, :no_intra_emphasis, :autolink, :underline, :highlight, :quote, :tables, :lax_spacing]
		Markdown.new(text, *options).to_html.html_safe
	end

	def no_markdown(text)
		markdown = Redcarpet::Markdown.new(Redcarpet::Render::StripDown)
		markdown.render(text)
	end
end

app/views/application/_admin_panel.html.erb
<div class="w3-section w3-container w3-topbar w3-bottombar w3-leftbar w3-rightbar w3-border-black w3-light-gray">
	<h2><i class="fas fa-user-lock"></i></h2>
	<%= yield %>
</div>

app/views/application/_button_link.html.erb
<%= link_to link_path, class: "w3-button w3-dark-gray w3-hover-green w3-round-large w3-right" do %>
	<%= link_text %> <i class="fas fa-caret-right"></i>
<% end %>

app/views/application/_category_summary_card.html.erb
<a href="<%= category_path(category) %>">
	<div class="w3-margin w3-display-container w3-hover-opacity hover-card">
		<%= image_tag 	category.photo.variant(resize_to_fill: [300,300]), 
						class: "w3-image w3-circle w3-card", 
						alt: category.title,
						loading: "lazy",
						width: "300",
						height: "300" %>
	</div>
</a>
<header class="w3-margin w3-center">
	<strong><%= category.title.upcase %></strong>
	<br>
	<i class="fas fa-list-alt"></i> <%= category.recipes.published.count %>
</header>

app/views/application/_hero_image.html.erb
<div class="hero-image">
</div>

app/views/application/_main_nav_bar.html.erb
<nav class="w3-center w3-dark-gray ">
	<nav class="w3-bar">
	  <%=  link_to root_path, class: "w3-bar-item w3-button w3-hover-green" do %>
	  	<i class="fas fa-home"></i><span class="w3-hide-small w3-hide-medium"> Home</span>
	  <% end %>
	  <%=  link_to recipes_path, class: "w3-bar-item w3-button w3-hover-green" do %> 
	  	<i class="fas fa-apple-alt"></i><span class="w3-hide-small w3-hide-medium"> Toutes les recettes</span>
	  <% end %>
	  <%= link_to categories_path, class: "w3-bar-item w3-button w3-hover-green" do %>
	  	<i class="fas fa-tags"></i><span class="w3-hide-small w3-hide-medium"> Toutes les catégories</span>
	  <% end %>
	</nav>	
</nav>

app/views/application/_recipe_summary_card.html.erb
<a href="<%= recipe_path(recipe) %>">
	<div class="w3-margin w3-display-container w3-hover-opacity hover-card">
		<%= image_tag 	recipe.photo.variant(resize_to_fill: [600,450]),
						class: "w3-image w3-round-xlarge w3-card", 
						alt: recipe.title,
						loading: "lazy",
						width: "600",
						height: "450" %>
		<header class="w3-display-bottomleft w3-margin w3-text-white">
			<strong><%= recipe.title.upcase %></strong>
			<br>
			<i>
			<%= complexity_human(recipe) %> |
			<%= global_time_human(recipe) %>
			</i>
		</header>
		<% if recipe.vegan? %>
			<div class="w3-display-topright w3-margin">
				<span class="w3-tag w3-green w3-round-large"><i class="fas fa-seedling"></i> VEGAN</span> 
			</div>
		<% end %>
	</div>
</a>

app/views/application/_recipes_search.html.erb
<%= form_tag(recipes_path, :method => "get") do %>
<%= text_field_tag :search, params[:search], placeholder: "Rechercher parmi toutes les recettes", class: "w3-input w3-border w3-round-xxlarge" %>
<% end %>